-- Create Table Supplier, Product, Supplies, Purchase_Order, Po_Line
-- Table Supplier (
CREATE TABLE SUPPLIER(
SUPNR CHAR(4) NOT NULL PRIMARY KEY, 
SUPNAME VARCHAR(40) NOT NULL, 
SUPADDRESS VARCHAR(50), 
SUPCITY VARCHAR(20), 
SUPSTATUS SMALLINT
)

CREATE TABLE PRODUCT(
PRODNR CHAR(6) NOT NULL PRIMARY KEY,
PRODNAME VARCHAR(60) NOT NULL,
CONSTRAINT UC1 UNIQUE(PRODNAME),
PRODTYPE VARCHAR(10),
CONSTRAINT CC1 CHECK(PRODTYPE IN ('white', 'red', 'rose','sparkling')),
AVAILABLE_QUANTITY INTEGER
)
-- CASCADE. It is used in conjunction with ON DELETE or ON UPDATE. It means that the child data is either deleted or updated when the parent data is deleted or updated. ... It means that the child data is set to NULL when the parent data is deleted or updated.
CREATE TABLE SUPPLIES(
SUPNR CHAR(4) NOT NULL,
PRODNR CHAR(6) NOT NULL,
PURCHASE_PRICE DECIMAL(8,2),
DELIV_PERIOD TIME,
PRIMARY KEY (SUPNR, PRODNR),
FOREIGN KEY (SUPNR) REFERENCES SUPPLIER (SUPNR)ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY (PRODNR) REFERENCES PRODUCT (PRODNR)ON DELETE CASCADE ON UPDATE CASCADE)

CREATE TABLE PURCHASE_ORDER(PONR CHAR(7) NOT NULL PRIMARY KEY, PODATE DATE,SUPNR CHAR(4) NOT NULL, FOREIGN KEY (SUPNR) REFERENCES SUPPLIER (SUPNR)ON DELETE CASCADE ON UPDATE CASCADE)

CREATE TABLE PO_LINE(PONR CHAR(7) NOT NULL, PRODNR CHAR(6) NOT NULL,QUANTITY INTEGER,PRIMARY KEY (PONR, PRODNR),FOREIGN KEY (PONR) REFERENCES PURCHASE_ORDER (PONR) ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY (PRODNR) REFERENCES PRODUCT (PRODNR) ON DELETE CASCADE ON UPDATE CASCADE)